import { Product, Category, Brand } from '../../src/models';
import { ProductStatus } from '../../src/enums';

const generateProducts = async () => {
    const categories = await Category.find();
    const brands = await Brand.find();

    const getCategoryId = (slug: string) => categories.find(c => c.slug === slug)?._id;
    const getBrandId = (slug: string) => brands.find(b => b.slug === slug)?._id;

    const products = [
        // Smartphones (10 products)
        {
            name: 'iPhone 15 Pro Max',
            nameAr: 'آيفون 15 برو ماكس',
            slug: 'iphone-15-pro-max',
            description: 'The most powerful iPhone ever with A17 Pro chip, titanium design, and advanced camera system.',
            descriptionAr: 'أقوى آيفون على الإطلاق مع شريحة A17 Pro وتصميم من التيتانيوم ونظام كاميرا متقدم.',
            shortDescription: 'Premium flagship smartphone with A17 Pro chip',
            shortDescriptionAr: 'هاتف رائد متميز مع شريحة A17 Pro',
            sku: 'IPH-15PM-256',
            price: 1199.99,
            compareAtPrice: 1299.99,
            quantity: 50,
            category: getCategoryId('smartphones'),
            brand: getBrandId('apple'),
            specifications: [
                { name: 'Display', value: '6.7" Super Retina XDR', group: 'Display' },
                { name: 'Chip', value: 'A17 Pro', group: 'Performance' },
                { name: 'Storage', value: '256GB', group: 'Storage' },
                { name: 'Battery', value: 'Up to 29 hours video', group: 'Power' },
            ],
            features: ['Titanium design', '5x optical zoom', 'Action button', 'USB-C'],
            featuresAr: ['تصميم تيتانيوم', 'زوم بصري 5x', 'زر الإجراء', 'USB-C'],
            tags: ['iphone', 'apple', 'flagship', '5g'],
            isFeatured: true,
            isNewArrival: true,
            averageRating: 4.8,
            reviewCount: 245,
        },
        {
            name: 'Samsung Galaxy S24 Ultra',
            nameAr: 'سامسونج جالاكسي S24 ألترا',
            slug: 'samsung-galaxy-s24-ultra',
            description: 'Ultimate Galaxy experience with AI-powered features and S Pen.',
            descriptionAr: 'تجربة Galaxy المثالية مع ميزات مدعومة بالذكاء الاصطناعي وقلم S Pen.',
            shortDescription: 'AI-powered flagship with S Pen',
            shortDescriptionAr: 'هاتف رائد مدعوم بالذكاء الاصطناعي مع S Pen',
            sku: 'SAM-S24U-256',
            price: 1299.99,
            compareAtPrice: 1399.99,
            quantity: 45,
            category: getCategoryId('smartphones'),
            brand: getBrandId('samsung'),
            specifications: [
                { name: 'Display', value: '6.8" Dynamic AMOLED 2X', group: 'Display' },
                { name: 'Processor', value: 'Snapdragon 8 Gen 3', group: 'Performance' },
                { name: 'RAM', value: '12GB', group: 'Memory' },
            ],
            features: ['Galaxy AI', 'S Pen included', '200MP camera', 'Titanium frame'],
            featuresAr: ['Galaxy AI', 'قلم S Pen مضمن', 'كاميرا 200MP', 'إطار تيتانيوم'],
            tags: ['samsung', 'galaxy', 'flagship', '5g', 's-pen'],
            isFeatured: true,
            isNewArrival: true,
            averageRating: 4.7,
            reviewCount: 189,
        },
        {
            name: 'Google Pixel 8 Pro',
            nameAr: 'جوجل بيكسل 8 برو',
            slug: 'google-pixel-8-pro',
            description: 'The best of Google AI in a beautiful, powerful phone.',
            descriptionAr: 'أفضل ذكاء اصطناعي من Google في هاتف جميل وقوي.',
            shortDescription: 'Pure Android experience with AI magic',
            shortDescriptionAr: 'تجربة أندرويد نقية مع سحر الذكاء الاصطناعي',
            sku: 'GOO-PX8P-256',
            price: 999.99,
            quantity: 35,
            category: getCategoryId('smartphones'),
            brand: getBrandId('google'),
            specifications: [
                { name: 'Display', value: '6.7" LTPO OLED', group: 'Display' },
                { name: 'Chip', value: 'Tensor G3', group: 'Performance' },
            ],
            features: ['Magic Eraser', '7 years of updates', 'Best-in-class AI'],
            featuresAr: ['ممحاة سحرية', '7 سنوات من التحديثات', 'أفضل ذكاء اصطناعي'],
            tags: ['google', 'pixel', 'android', 'ai'],
            isFeatured: true,
            averageRating: 4.6,
            reviewCount: 156,
        },
        {
            name: 'OnePlus 12',
            nameAr: 'ون بلس 12',
            slug: 'oneplus-12',
            description: 'Flagship killer with Hasselblad camera and fast charging.',
            descriptionAr: 'قاتل الهواتف الرائدة مع كاميرا Hasselblad وشحن سريع.',
            shortDescription: 'High-performance flagship at great value',
            shortDescriptionAr: 'هاتف رائد عالي الأداء بقيمة رائعة',
            sku: 'OP-12-256',
            price: 799.99,
            compareAtPrice: 899.99,
            quantity: 40,
            category: getCategoryId('smartphones'),
            brand: getBrandId('oneplus'),
            features: ['100W charging', 'Hasselblad camera', '120Hz display'],
            featuresAr: ['شحن 100W', 'كاميرا Hasselblad', 'شاشة 120Hz'],
            tags: ['oneplus', 'flagship', 'fast-charging'],
            averageRating: 4.5,
            reviewCount: 98,
        },
        {
            name: 'Xiaomi 14 Ultra',
            nameAr: 'شاومي 14 ألترا',
            slug: 'xiaomi-14-ultra',
            description: 'Photography-focused flagship with Leica optics.',
            descriptionAr: 'هاتف رائد يركز على التصوير مع عدسات Leica.',
            shortDescription: 'Leica camera phone excellence',
            shortDescriptionAr: 'تميز هاتف كاميرا Leica',
            sku: 'XIA-14U-512',
            price: 1099.99,
            quantity: 25,
            category: getCategoryId('smartphones'),
            brand: getBrandId('xiaomi'),
            tags: ['xiaomi', 'leica', 'photography'],
            isFeatured: true,
            averageRating: 4.6,
            reviewCount: 67,
        },

        // Laptops (10 products)
        {
            name: 'MacBook Pro 16" M3 Max',
            nameAr: 'ماك بوك برو 16 بوصة M3 Max',
            slug: 'macbook-pro-16-m3-max',
            description: 'The most powerful MacBook Pro ever with M3 Max chip for demanding workflows.',
            descriptionAr: 'أقوى ماك بوك برو على الإطلاق مع شريحة M3 Max لأعباء العمل المتطلبة.',
            shortDescription: 'Professional laptop with M3 Max',
            shortDescriptionAr: 'لابتوب احترافي مع M3 Max',
            sku: 'MBP-16-M3MAX',
            price: 3499.99,
            quantity: 20,
            category: getCategoryId('laptops'),
            brand: getBrandId('apple'),
            specifications: [
                { name: 'Chip', value: 'Apple M3 Max', group: 'Performance' },
                { name: 'Memory', value: '36GB Unified', group: 'Memory' },
                { name: 'Storage', value: '1TB SSD', group: 'Storage' },
                { name: 'Display', value: '16.2" Liquid Retina XDR', group: 'Display' },
            ],
            features: ['Up to 22 hours battery', 'ProMotion display', 'MagSafe charging'],
            featuresAr: ['حتى 22 ساعة بطارية', 'شاشة ProMotion', 'شحن MagSafe'],
            tags: ['macbook', 'apple', 'professional', 'm3'],
            isFeatured: true,
            averageRating: 4.9,
            reviewCount: 134,
        },
        {
            name: 'Dell XPS 15',
            nameAr: 'ديل XPS 15',
            slug: 'dell-xps-15',
            description: 'Stunning InfinityEdge display with powerful Intel Core Ultra processor.',
            descriptionAr: 'شاشة InfinityEdge مذهلة مع معالج Intel Core Ultra قوي.',
            shortDescription: 'Premium Windows ultrabook',
            shortDescriptionAr: 'ألترا بوك ويندوز متميز',
            sku: 'DELL-XPS15-I7',
            price: 1799.99,
            compareAtPrice: 1999.99,
            quantity: 30,
            category: getCategoryId('laptops'),
            brand: getBrandId('dell'),
            tags: ['dell', 'xps', 'ultrabook', 'windows'],
            isFeatured: true,
            averageRating: 4.6,
            reviewCount: 89,
        },
        {
            name: 'ASUS ROG Zephyrus G16',
            nameAr: 'أسوس ROG Zephyrus G16',
            slug: 'asus-rog-zephyrus-g16',
            description: 'Ultra-slim gaming laptop with RTX 4070 and OLED display.',
            descriptionAr: 'لابتوب ألعاب رفيع للغاية مع RTX 4070 وشاشة OLED.',
            shortDescription: 'Thin gaming powerhouse',
            shortDescriptionAr: 'قوة ألعاب رفيعة',
            sku: 'ASUS-ROG-G16',
            price: 2299.99,
            quantity: 25,
            category: getCategoryId('laptops'),
            brand: getBrandId('asus'),
            tags: ['asus', 'rog', 'gaming', 'rtx4070'],
            isFeatured: true,
            averageRating: 4.7,
            reviewCount: 76,
        },
        {
            name: 'HP Spectre x360',
            nameAr: 'HP Spectre x360',
            slug: 'hp-spectre-x360',
            description: 'Convertible 2-in-1 laptop with gem-cut design.',
            descriptionAr: 'لابتوب 2 في 1 قابل للتحويل بتصميم مقطوع كالجوهرة.',
            shortDescription: 'Elegant convertible laptop',
            shortDescriptionAr: 'لابتوب قابل للتحويل أنيق',
            sku: 'HP-SPEC-X360',
            price: 1599.99,
            quantity: 20,
            category: getCategoryId('laptops'),
            brand: getBrandId('hp'),
            tags: ['hp', 'spectre', '2in1', 'convertible'],
            averageRating: 4.5,
            reviewCount: 54,
        },
        {
            name: 'Lenovo ThinkPad X1 Carbon',
            nameAr: 'لينوفو ثينك باد X1 Carbon',
            slug: 'lenovo-thinkpad-x1-carbon',
            description: 'Business ultrabook with legendary ThinkPad reliability.',
            descriptionAr: 'ألترا بوك أعمال مع موثوقية ThinkPad الأسطورية.',
            shortDescription: 'Premium business laptop',
            shortDescriptionAr: 'لابتوب أعمال متميز',
            sku: 'LEN-X1C-G11',
            price: 1899.99,
            quantity: 15,
            category: getCategoryId('laptops'),
            brand: getBrandId('lenovo'),
            tags: ['lenovo', 'thinkpad', 'business', 'ultrabook'],
            averageRating: 4.7,
            reviewCount: 112,
        },

        // TVs (8 products)
        {
            name: 'LG C4 65" OLED 4K TV',
            nameAr: 'LG C4 65 بوصة OLED 4K TV',
            slug: 'lg-c4-65-oled-4k',
            description: 'Stunning OLED display with perfect blacks and vibrant colors.',
            descriptionAr: 'شاشة OLED مذهلة مع ألوان سوداء مثالية وألوان نابضة بالحياة.',
            shortDescription: 'Premium OLED entertainment',
            shortDescriptionAr: 'ترفيه OLED متميز',
            sku: 'LG-C4-65-OLED',
            price: 1799.99,
            compareAtPrice: 2099.99,
            quantity: 15,
            category: getCategoryId('tvs-displays'),
            brand: getBrandId('lg'),
            tags: ['lg', 'oled', '4k', 'smart-tv'],
            isFeatured: true,
            averageRating: 4.8,
            reviewCount: 203,
        },
        {
            name: 'Samsung 75" Neo QLED 8K',
            nameAr: 'سامسونج 75 بوصة Neo QLED 8K',
            slug: 'samsung-75-neo-qled-8k',
            description: 'Next-level 8K resolution with Quantum Matrix Technology.',
            descriptionAr: 'دقة 8K بالمستوى التالي مع تقنية Quantum Matrix.',
            shortDescription: 'Ultimate 8K experience',
            shortDescriptionAr: 'تجربة 8K المثالية',
            sku: 'SAM-NEO-75-8K',
            price: 3999.99,
            quantity: 8,
            category: getCategoryId('tvs-displays'),
            brand: getBrandId('samsung'),
            tags: ['samsung', 'neo-qled', '8k', 'premium'],
            isFeatured: true,
            averageRating: 4.6,
            reviewCount: 45,
        },
        {
            name: 'Sony A95L 55" QD-OLED',
            nameAr: 'سوني A95L 55 بوصة QD-OLED',
            slug: 'sony-a95l-55-qd-oled',
            description: 'Cognitive Processor XR for the ultimate picture quality.',
            descriptionAr: 'معالج Cognitive XR لجودة صورة مثالية.',
            shortDescription: 'Top-tier QD-OLED',
            shortDescriptionAr: 'QD-OLED من الدرجة الأولى',
            sku: 'SONY-A95L-55',
            price: 2499.99,
            quantity: 12,
            category: getCategoryId('tvs-displays'),
            brand: getBrandId('sony'),
            tags: ['sony', 'qd-oled', 'premium'],
            isFeatured: true,
            averageRating: 4.9,
            reviewCount: 78,
        },

        // Audio (8 products)
        {
            name: 'Sony WH-1000XM5',
            nameAr: 'سوني WH-1000XM5',
            slug: 'sony-wh-1000xm5',
            description: 'Industry-leading noise cancellation with premium sound.',
            descriptionAr: 'إلغاء ضوضاء رائد في الصناعة مع صوت متميز.',
            shortDescription: 'Best noise-cancelling headphones',
            shortDescriptionAr: 'أفضل سماعات إلغاء الضوضاء',
            sku: 'SONY-WH1000XM5',
            price: 349.99,
            compareAtPrice: 399.99,
            quantity: 60,
            category: getCategoryId('audio'),
            brand: getBrandId('sony'),
            tags: ['sony', 'headphones', 'anc', 'wireless'],
            isFeatured: true,
            averageRating: 4.8,
            reviewCount: 567,
        },
        {
            name: 'Apple AirPods Pro 2',
            nameAr: 'أبل إير بودز برو 2',
            slug: 'apple-airpods-pro-2',
            description: 'Active Noise Cancellation with Adaptive Transparency.',
            descriptionAr: 'إلغاء ضوضاء نشط مع شفافية تكيفية.',
            shortDescription: 'Premium wireless earbuds',
            shortDescriptionAr: 'سماعات أذن لاسلكية متميزة',
            sku: 'AAPL-APP2',
            price: 249.99,
            quantity: 100,
            category: getCategoryId('audio'),
            brand: getBrandId('apple'),
            tags: ['apple', 'airpods', 'earbuds', 'anc'],
            isFeatured: true,
            averageRating: 4.7,
            reviewCount: 890,
        },
        {
            name: 'Bose QuietComfort Ultra',
            nameAr: 'بوز QuietComfort Ultra',
            slug: 'bose-quietcomfort-ultra',
            description: 'Immersive Audio with world-class noise cancellation.',
            descriptionAr: 'صوت غامر مع إلغاء ضوضاء عالمي المستوى.',
            shortDescription: 'Premium Bose experience',
            shortDescriptionAr: 'تجربة Bose متميزة',
            sku: 'BOSE-QC-ULTRA',
            price: 429.99,
            quantity: 40,
            category: getCategoryId('audio'),
            brand: getBrandId('bose'),
            tags: ['bose', 'headphones', 'anc', 'premium'],
            isFeatured: true,
            averageRating: 4.7,
            reviewCount: 234,
        },
        {
            name: 'JBL Charge 5',
            nameAr: 'JBL Charge 5',
            slug: 'jbl-charge-5',
            description: 'Portable Bluetooth speaker with powerbank function.',
            descriptionAr: 'مكبر صوت بلوتوث محمول مع وظيفة شاحن متنقل.',
            shortDescription: 'Waterproof portable speaker',
            shortDescriptionAr: 'مكبر صوت محمول مقاوم للماء',
            sku: 'JBL-CHARGE5',
            price: 179.99,
            compareAtPrice: 199.99,
            quantity: 80,
            category: getCategoryId('audio'),
            brand: getBrandId('jbl'),
            tags: ['jbl', 'speaker', 'portable', 'waterproof'],
            averageRating: 4.6,
            reviewCount: 456,
        },

        // Gaming (8 products)
        {
            name: 'PlayStation 5',
            nameAr: 'بلاي ستيشن 5',
            slug: 'playstation-5',
            description: 'Next-gen gaming with lightning-fast SSD and DualSense controller.',
            descriptionAr: 'ألعاب الجيل القادم مع SSD سريع البرق ووحدة تحكم DualSense.',
            shortDescription: 'Next-gen gaming console',
            shortDescriptionAr: 'وحدة ألعاب الجيل القادم',
            sku: 'SONY-PS5-STD',
            price: 499.99,
            quantity: 30,
            category: getCategoryId('gaming'),
            brand: getBrandId('sony'),
            tags: ['playstation', 'ps5', 'console', 'gaming'],
            isFeatured: true,
            averageRating: 4.9,
            reviewCount: 1234,
        },
        {
            name: 'Xbox Series X',
            nameAr: 'إكس بوكس سيريس إكس',
            slug: 'xbox-series-x',
            description: 'The most powerful Xbox ever with 4K gaming at 120fps.',
            descriptionAr: 'أقوى إكس بوكس على الإطلاق مع ألعاب 4K بمعدل 120 إطار.',
            shortDescription: 'Most powerful Xbox',
            shortDescriptionAr: 'أقوى إكس بوكس',
            sku: 'MS-XBOX-SX',
            price: 499.99,
            quantity: 25,
            category: getCategoryId('gaming'),
            brand: getBrandId('microsoft'),
            tags: ['xbox', 'console', 'gaming', '4k'],
            isFeatured: true,
            averageRating: 4.8,
            reviewCount: 876,
        },
        {
            name: 'Nintendo Switch OLED',
            nameAr: 'نينتندو سويتش OLED',
            slug: 'nintendo-switch-oled',
            description: 'Vivid OLED screen with enhanced audio and wide adjustable stand.',
            descriptionAr: 'شاشة OLED حية مع صوت محسن وحامل قابل للتعديل.',
            shortDescription: 'Portable gaming with OLED',
            shortDescriptionAr: 'ألعاب محمولة مع OLED',
            sku: 'NIN-SWITCH-OLED',
            price: 349.99,
            quantity: 45,
            category: getCategoryId('gaming'),
            brand: getBrandId('nintendo'),
            tags: ['nintendo', 'switch', 'portable', 'oled'],
            isFeatured: true,
            averageRating: 4.7,
            reviewCount: 543,
        },
        {
            name: 'Razer BlackWidow V4 Pro',
            nameAr: 'رازر بلاك ويدو V4 برو',
            slug: 'razer-blackwidow-v4-pro',
            description: 'Premium mechanical gaming keyboard with Razer Green switches.',
            descriptionAr: 'لوحة مفاتيح ألعاب ميكانيكية متميزة مع مفاتيح Razer Green.',
            shortDescription: 'Pro-grade gaming keyboard',
            shortDescriptionAr: 'لوحة مفاتيح ألعاب احترافية',
            sku: 'RAZ-BWID-V4P',
            price: 229.99,
            quantity: 35,
            category: getCategoryId('gaming'),
            brand: getBrandId('razer'),
            tags: ['razer', 'keyboard', 'mechanical', 'rgb'],
            averageRating: 4.6,
            reviewCount: 189,
        },

        // Wearables (6 products)
        {
            name: 'Apple Watch Ultra 2',
            nameAr: 'أبل واتش ألترا 2',
            slug: 'apple-watch-ultra-2',
            description: 'The most rugged and capable Apple Watch for extreme adventures.',
            descriptionAr: 'أكثر أبل واتش متانة وقدرة للمغامرات المتطرفة.',
            shortDescription: 'Adventure-ready smartwatch',
            shortDescriptionAr: 'ساعة ذكية جاهزة للمغامرة',
            sku: 'AAPL-AWU2-49',
            price: 799.99,
            quantity: 35,
            category: getCategoryId('wearables'),
            brand: getBrandId('apple'),
            tags: ['apple', 'watch', 'ultra', 'fitness'],
            isFeatured: true,
            averageRating: 4.8,
            reviewCount: 234,
        },
        {
            name: 'Samsung Galaxy Watch 6 Classic',
            nameAr: 'سامسونج جالاكسي واتش 6 كلاسيك',
            slug: 'samsung-galaxy-watch-6-classic',
            description: 'Premium smartwatch with rotating bezel and health monitoring.',
            descriptionAr: 'ساعة ذكية متميزة مع إطار دوار ومراقبة الصحة.',
            shortDescription: 'Classic smartwatch design',
            shortDescriptionAr: 'تصميم ساعة ذكية كلاسيكي',
            sku: 'SAM-GW6C-47',
            price: 429.99,
            quantity: 40,
            category: getCategoryId('wearables'),
            brand: getBrandId('samsung'),
            tags: ['samsung', 'watch', 'classic', 'health'],
            averageRating: 4.5,
            reviewCount: 156,
        },

        // Cameras (5 products)
        {
            name: 'Sony Alpha a7 IV',
            nameAr: 'سوني ألفا a7 IV',
            slug: 'sony-alpha-a7-iv',
            description: 'Full-frame mirrorless camera with advanced autofocus.',
            descriptionAr: 'كاميرا بدون مرآة بإطار كامل مع تركيز تلقائي متقدم.',
            shortDescription: 'Professional full-frame camera',
            shortDescriptionAr: 'كاميرا إطار كامل احترافية',
            sku: 'SONY-A7IV-BODY',
            price: 2499.99,
            quantity: 15,
            category: getCategoryId('cameras'),
            brand: getBrandId('sony'),
            tags: ['sony', 'alpha', 'mirrorless', 'full-frame'],
            isFeatured: true,
            averageRating: 4.8,
            reviewCount: 167,
        },
        {
            name: 'Canon EOS R6 Mark II',
            nameAr: 'كانون EOS R6 Mark II',
            slug: 'canon-eos-r6-mark-ii',
            description: 'High-speed full-frame mirrorless with 40fps continuous shooting.',
            descriptionAr: 'كاميرا بدون مرآة بإطار كامل عالية السرعة مع تصوير مستمر 40 إطار.',
            shortDescription: 'High-speed mirrorless',
            shortDescriptionAr: 'بدون مرآة عالية السرعة',
            sku: 'CAN-R6M2-BODY',
            price: 2499.99,
            quantity: 12,
            category: getCategoryId('cameras'),
            brand: getBrandId('canon'),
            tags: ['canon', 'eos', 'mirrorless', 'high-speed'],
            isFeatured: true,
            averageRating: 4.7,
            reviewCount: 98,
        },
    ];

    return products.map(p => ({
        ...p,
        status: ProductStatus.ACTIVE,
        isActive: true,
        images: [],
        lowStockThreshold: 10,
    }));
};

export const seedProducts = async (): Promise<void> => {
    const existingCount = await Product.countDocuments();
    if (existingCount > 0) {
        console.log(`   ⏭️  ${existingCount} products already exist, skipping...`);
        return;
    }

    const products = await generateProducts();
    await Product.insertMany(products);
    console.log(`   ✓ Created ${products.length} products`);

    // Update category product counts
    const categories = await Category.find();
    for (const category of categories) {
        const count = await Product.countDocuments({ category: category._id });
        await Category.findByIdAndUpdate(category._id, { productCount: count });
    }

    // Update brand product counts
    const brands = await Brand.find();
    for (const brand of brands) {
        const count = await Product.countDocuments({ brand: brand._id });
        await Brand.findByIdAndUpdate(brand._id, { productCount: count });
    }

    console.log(`   ✓ Updated category and brand product counts`);
};
